general:
  zk_connect: '127.0.0.1:2181'
  aws_access: 'R49X6JP_ZTZZ0WIP5SFV'
  aws_secret: 'MSs3Awp-w4yNl-KLSVstN2YlYGiFCVi_ATh96w=='
  aws_bucket: 'malware'
  sequence_file_length: 4
  max_multiple_seq_file: 2
  max_seq_file_size: 1000
loaders:
  - yara
  - clamscan